name: CI

on:
 push:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install

      - name: Build
        run: npm run build

      - name: Check if dependencies up to date
        run: npm run checkDependencyUpdates
